### ISSUE TITLE
1.9

### ISSUE THREAD

**Issue by EMPxRubix** [djfun/mc-map-item-tool#15]
Hey
With the new 1.9 snapshots something in the map_[i].dat changed and it doesnt work in theese versions.

Pls add an option to get the map_[i].dat files 1.9 compatible

**Comment by EMPxRubix** [comment]
Great Job btw ^^

**Comment by djfun** [comment]
I just tried the newest snapshot (15w35e) and successfully imported a map item. In the maps created by minecraft there seems to be a new byte tag "trackingPosition", I don't notice any problems though when using a map item created by my tool.
Can you give a short summary of what you are trying to do, what is not working and what snapshot version you are using so that I can reproduce the issue and see what needs to be fixed.

**Comment by EMPxRubix** [comment]
I did it with NBTexplorer import the binary string into a generated map file of the snapshot
sry for bad english

**Comment by djfun** [comment]
No worries. What did you expect to happen and what did actually happen?

**Comment by EMPxRubix** [comment]
i imported the map_[i].dat and replaced the old one.
this is the result: http://puu.sh/jWmWj/e3840b9735.png 
(not the Image i wanted ^^)

**Comment by djfun** [comment]
> What did you expect to happen [..]
Can you give me the picture you selected in the mc-map-tool? And how does it behave differently in the 1.8 versions of Minecraft?

**Comment by EMPxRubix** [comment]
http://puu.sh/jWnWy/1e44d4771f.png

**Comment by djfun** [comment]
From your screenshot I see that you used x=0 and z=0 in the settings to create the map.
If you are at these coordinates in minecraft (might be near spawn) and look at the map item it gets updated to show the area instead of the picture.

You can just set these to a set of coordinates where no one in your map will go (like far out at 500000,500000 or so) and you should be good.

**Comment by EMPxRubix** [comment]
ok yes i build at 0 250 0...
My fault sry
